### ISSUE TITLE
Simple install on windows failing

### ISSUE THREAD

**Issue by Jonarod** [D1no/touch2s#10]
Hello,
After cloning the repo, I just ran `meteor` and this is what I get from the console

`C:\Users\Yoga\AppData\Local\.meteor\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fibers\future.js:245
                                                throw(ex);
                                                      ^
Error: No metadata files found for isopack at: /C/Users/Yoga/AppData/Local/.meteor/packages/webpack_webpack/0.4.4
    at [object Object]._.extend._loadUnibuildsFromPath (C:\tools\isobuild\isopack.js:879:13)
    at C:\tools\packaging\tropohouse.js:500:19
    at Array.forEach (native)
    at Function._.each._.forEach (C:\Users\Yoga\AppData\Local\.meteor\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:79:11)
    at C:\tools\packaging\tropohouse.js:499:11
    at C:\tools\utils\buildmessage.js:356:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at C:\tools\utils\buildmessage.js:349:34
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at C:\tools\utils\buildmessage.js:347:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:321:26)
    at Object.download (C:\tools\packaging\tropohouse.js:437:20)
    at C:\tools\packaging\tropohouse.js:575:22
    at C:\tools\utils\buildmessage.js:356:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at C:\tools\utils\buildmessage.js:349:34
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at C:\tools\utils\buildmessage.js:347:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:321:26)
    at [object Object]._.extend.downloadPackagesMissingFromMap (C:\tools\packaging\tropohouse.js:572:20)
    at C:\tools\project-context.js:702:25
    at C:\tools\utils\buildmessage.js:356:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at C:\tools\utils\buildmessage.js:349:34
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at C:\tools\utils\buildmessage.js:347:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:321:26)
    at C:\tools\project-context.js:701:20
    at C:\tools\packaging\catalog\catalog.js:100:5
    at C:\tools\utils\buildmessage.js:268:13
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at C:\tools\utils\buildmessage.js:261:29
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at C:\tools\utils\buildmessage.js:259:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at C:\tools\utils\buildmessage.js:250:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at Object.capture (C:\tools\utils\buildmessage.js:249:19)
    at Object.catalog.runAndRetryWithRefreshIfHelpful (C:\tools\packaging\catalog\catalog.js:99:31)
    at ProjectContext._.extend._downloadMissingPackages (C:\tools\project-context.js:700:13)
    at C:\tools\project-context.js:257:35
    at C:\tools\utils\buildmessage.js:356:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at C:\tools\utils\buildmessage.js:349:34
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at C:\tools\utils\buildmessage.js:347:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:321:26)
    at ProjectContext._.extend._completeStagesThrough (C:\tools\project-context.js:247:18)
    at ProjectContext._.extend.saveChangedMetadata (C:\tools\project-context.js:235:10)
    at ProjectContext._.extend.prepareProjectForBuild (C:\tools\project-context.js:240:10)
    at C:\tools\runners\run-app.js:517:29
    at C:\tools\utils\buildmessage.js:268:13
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at C:\tools\utils\buildmessage.js:261:29
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at C:\tools\utils\buildmessage.js:259:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at C:\tools\utils\buildmessage.js:250:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at Object.capture (C:\tools\utils\buildmessage.js:249:19)
    at bundleApp (C:\tools\runners\run-app.js:516:31)
    at [object Object]._.extend._runOnce (C:\tools\runners\run-app.js:594:35)
    at [object Object]._.extend._fiber (C:\tools\runners\run-app.js:858:28)
    at C:\tools\runners\run-app.js:396:12`

I have been reinstalling meteor twice and cloned the repo twice as well.
Any idea??

Thank you !!

**Comment by D1no** [comment]
Yeah, this has nothing to do with the repo. The current beta releases and release candidates of meteor are simply not running (yet) on windows. Please check out the issues in the official meteor github repository.
