### ISSUE TITLE
Error on running it locally

### ISSUE THREAD

**Issue by manrajgrover** [D1no/touch2s#2]
It is throwing the following error while running it locally. I believe its because settings.json file is missing.

```
I20160110-22:36:01.167(5.5)? Info: The demo bot is running. Uncomment him in server/todo-publications.js
I20160110-22:36:15.587(5.5)? Demo: Bot is annoyed by tasks count
I20160110-22:36:15.638(5.5)? Exception in setInterval callback: TypeError: Cannot read property 'username' of undefined
I20160110-22:36:15.639(5.5)?     at webpack:///home/manraj/github/touch2s/modules/TodoApp/server/todo-publications.js:54:40
I20160110-22:36:15.639(5.5)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20160110-22:36:15.639(5.5)?     at packages/meteor/timers.js:6:1
I20160110-22:36:15.640(5.5)?     at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1)
```

If yes, I guess it should be added to documentation. If no, please help.

**Comment by D1no** [comment]
Thanks for the catch. This was an unnecessary username & password assignment for the quick demo-bot. A `settings.json` is optional.

**Comment by manrajgrover** [comment]
@D1no Wow, thanks for a quick reply. I'll try it again and let you know if there's any issue.
